CREATE TABLE `users` (
  `user_id` BIGINT NOT NULL,
  `login_id` VARCHAR(64) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `role` VARCHAR(30) NOT NULL,
  `status` VARCHAR(30) NOT NULL,
  `locale` VARCHAR(2) NOT NULL DEFAULT 'EN',
  `last_login_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `ck_users_locale` CHECK (`locale` IN ('EN', 'KO')),
  UNIQUE KEY `uq_users_login_id_active` (`login_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `endpoints` (
  `endpoint_id` BIGINT NOT NULL,
  `agent_id` VARCHAR(64) NOT NULL,
  `hostname` VARCHAR(255) NOT NULL,
  `os_type` VARCHAR(30) NOT NULL,
  `os_version` VARCHAR(100) NULL,
  `ip_address` VARCHAR(45) NULL,
  `agent_version` VARCHAR(50) NULL,
  `agent_build_id` VARCHAR(200) NULL,
  `agent_arch` VARCHAR(20) NULL,
  `capability_codes_json` LONGTEXT NOT NULL,
  `sensor_health_json` LONGTEXT NOT NULL,
  `registered_at` DATETIME NOT NULL,
  `status` VARCHAR(30) NOT NULL,
  `last_seen_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`endpoint_id`),
  UNIQUE KEY `uq_endpoints_agent_id` (`agent_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `agent_auth_keys` (
  `agent_auth_key_id` BIGINT NOT NULL,
  `endpoint_id` BIGINT NOT NULL,
  `cert_fingerprint` VARCHAR(128) NOT NULL,
  `cert_subject` VARCHAR(500) NOT NULL,
  `cert_san_agent_id` VARCHAR(64) NOT NULL,
  `issued_at` DATETIME NOT NULL,
  `expires_at` DATETIME NOT NULL,
  `revoked_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`agent_auth_key_id`),
  UNIQUE KEY `uq_agent_auth_keys_fingerprint` (`cert_fingerprint`),
  KEY `idx_agent_auth_keys_endpoint` (`endpoint_id`),
  CONSTRAINT `fk_agent_auth_keys_endpoint` FOREIGN KEY (`endpoint_id`) REFERENCES `endpoints` (`endpoint_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `audit_logs` (
  `audit_log_id` BIGINT NOT NULL,
  `actor_type` VARCHAR(30) NOT NULL,
  `actor_identifier` VARCHAR(255) NOT NULL,
  `action` VARCHAR(100) NOT NULL,
  `resource_type` VARCHAR(50) NOT NULL,
  `resource_id` VARCHAR(255) NOT NULL,
  `before_json` LONGTEXT NULL,
  `after_json` LONGTEXT NULL,
  `request_id` VARCHAR(100) NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`audit_log_id`),
  KEY `idx_audit_logs_resource_created` (`resource_type`, `resource_id`, `created_at`),
  KEY `idx_audit_logs_request_id` (`request_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `ingest_metadata` (
  `endpoint_id` BIGINT NOT NULL,
  `bucket_start_at` DATETIME NOT NULL,
  `bucket_end_at` DATETIME NOT NULL,
  `storage_backend` VARCHAR(30) NOT NULL,
  `storage_class` VARCHAR(50) NOT NULL,
  `storage_status` VARCHAR(30) NOT NULL,
  `storage_path` VARCHAR(1000) NOT NULL,
  `event_count` BIGINT NOT NULL DEFAULT 0,
  `size_bytes` BIGINT NULL,
  `checksum_sha256` CHAR(64) NULL,
  `archived_at` DATETIME NULL,
  `archive_verified_at` DATETIME NULL,
  `restore_requested_at` DATETIME NULL,
  `restored_at` DATETIME NULL,
  `restore_expires_at` DATETIME NULL,
  `last_error` TEXT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`endpoint_id`, `bucket_start_at`, `storage_backend`, `storage_class`),
  UNIQUE KEY `uq_ingest_metadata_storage_path` (`storage_backend`, `storage_path`),
  CONSTRAINT `fk_ingest_metadata_endpoint` FOREIGN KEY (`endpoint_id`) REFERENCES `endpoints` (`endpoint_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `local_event_buffer` (
  `local_event_buffer_id` BIGINT NOT NULL,
  `endpoint_id` BIGINT NULL,
  `event_id` CHAR(36) NOT NULL,
  `batch_id` CHAR(36) NULL,
  `event_type` VARCHAR(50) NOT NULL,
  `payload_json` LONGTEXT NOT NULL,
  `collected_at` DATETIME NOT NULL,
  `status` VARCHAR(30) NOT NULL DEFAULT 'PENDING',
  `retry_count` INT NOT NULL DEFAULT 0,
  `last_error` TEXT NULL,
  `next_retry_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`local_event_buffer_id`),
  UNIQUE KEY `uq_local_event_buffer_event_id` (`event_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `event_failures` (
  `failure_id` CHAR(36) NOT NULL,
  `event_id` CHAR(36) NULL,
  `endpoint_id` BIGINT NULL,
  `source_topic` VARCHAR(200) NOT NULL,
  `source_partition` INT NOT NULL,
  `source_offset` BIGINT NOT NULL,
  `consumer_name` VARCHAR(100) NOT NULL,
  `failure_stage` VARCHAR(100) NOT NULL,
  `failure_code` VARCHAR(100) NULL,
  `error_message` TEXT NOT NULL,
  `retryable` TINYINT(1) NOT NULL,
  `retry_count` INT NOT NULL DEFAULT 0,
  `payload_object_key` VARCHAR(1000) NOT NULL,
  `payload_sha256` CHAR(64) NOT NULL,
  `payload_size_bytes` BIGINT NOT NULL,
  `status` VARCHAR(30) NOT NULL,
  `failed_at` DATETIME NOT NULL,
  `replay_count` INT NOT NULL DEFAULT 0,
  `last_replayed_at` DATETIME NULL,
  `reprocess_outcome` VARCHAR(100) NULL,
  `resolved_at` DATETIME NULL,
  `retention_expires_at` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`failure_id`),
  KEY `idx_event_failures_endpoint_failed` (`endpoint_id`, `failed_at`),
  KEY `idx_event_failures_status_failed` (`status`, `failed_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `edr_events` (
  `event_id` CHAR(36) NOT NULL,
  `batch_id` CHAR(36) NOT NULL,
  `endpoint_id` BIGINT NOT NULL,
  `agent_id` VARCHAR(64) NOT NULL,
  `hostname` VARCHAR(255) NOT NULL,
  `os_type` VARCHAR(30) NOT NULL,
  `ip_address` VARCHAR(45) NULL,
  `event_type` VARCHAR(50) NOT NULL,
  `occurred_at` DATETIME NOT NULL,
  `ingested_at` DATETIME NOT NULL,
  `process_name` VARCHAR(255) NULL,
  `process_path` VARCHAR(1000) NULL,
  `pid` BIGINT NULL,
  `ppid` BIGINT NULL,
  `command_line` TEXT NULL,
  `user_name` VARCHAR(255) NULL,
  `file_path` VARCHAR(1000) NULL,
  `file_action` VARCHAR(50) NULL,
  `file_hash_sha256` CHAR(64) NULL,
  `remote_ip` VARCHAR(45) NULL,
  `remote_domain` VARCHAR(255) NULL,
  `remote_port` INT NULL,
  `protocol` VARCHAR(30) NULL,
  `dns_query` VARCHAR(500) NULL,
  `dns_record_type` VARCHAR(20) NULL,
  `dns_response_code` VARCHAR(30) NULL,
  `dns_answers_json` LONGTEXT NULL,
  `l7_protocol` VARCHAR(30) NULL,
  `http_method` VARCHAR(20) NULL,
  `http_host` VARCHAR(500) NULL,
  `url` TEXT NULL,
  `http_status_code` INT NULL,
  `http_user_agent` TEXT NULL,
  `tls_sni` VARCHAR(500) NULL,
  `tls_version` VARCHAR(30) NULL,
  `tls_certificate_subject` VARCHAR(1000) NULL,
  `tls_certificate_issuer` VARCHAR(1000) NULL,
  `tls_certificate_sha256` CHAR(64) NULL,
  `raw_payload` LONGTEXT NOT NULL,
  `payload_sha256` CHAR(64) NOT NULL,
  `schema_version` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`endpoint_id`, `occurred_at`, `event_type`, `event_id`),
  UNIQUE KEY `uq_edr_events_event_id` (`event_id`),
  KEY `idx_edr_events_type_occurred` (`event_type`, `occurred_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `alerts` (
  `alert_id` BIGINT NOT NULL,
  `endpoint_id` BIGINT NOT NULL,
  `event_id` CHAR(36) NOT NULL,
  `event_occurred_at` DATETIME NOT NULL,
  `batch_id` CHAR(36) NULL,
  `agent_id` VARCHAR(64) NOT NULL,
  `rule_code` VARCHAR(100) NOT NULL,
  `rule_name` VARCHAR(200) NOT NULL,
  `rule_version` INT NOT NULL,
  `mitre_tactic_code` VARCHAR(20) NOT NULL,
  `mitre_tactic_name` VARCHAR(100) NOT NULL,
  `mitre_technique_code` VARCHAR(30) NOT NULL,
  `mitre_technique_name` VARCHAR(200) NOT NULL,
  `title` VARCHAR(200) NOT NULL,
  `summary` TEXT NOT NULL,
  `severity` VARCHAR(20) NOT NULL,
  `risk_score` DECIMAL(5,2) NOT NULL,
  `status` VARCHAR(30) NOT NULL,
  `detected_at` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`alert_id`),
  UNIQUE KEY `uq_alerts_event_rule` (`event_id`, `rule_code`, `rule_version`),
  KEY `idx_alerts_endpoint_detected` (`endpoint_id`, `detected_at`),
  CONSTRAINT `fk_alerts_endpoint` FOREIGN KEY (`endpoint_id`) REFERENCES `endpoints` (`endpoint_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `incidents` (
  `incident_id` BIGINT NOT NULL,
  `endpoint_id` BIGINT NOT NULL,
  `correlation_key` VARCHAR(255) NOT NULL,
  `window_start_at` DATETIME NOT NULL,
  `window_end_at` DATETIME NOT NULL,
  `title` VARCHAR(200) NOT NULL,
  `description` TEXT NULL,
  `severity` VARCHAR(20) NOT NULL,
  `status` VARCHAR(30) NOT NULL,
  `first_detected_at` DATETIME NOT NULL,
  `last_detected_at` DATETIME NOT NULL,
  `closed_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`incident_id`),
  UNIQUE KEY `uq_incidents_correlation` (`endpoint_id`, `correlation_key`, `window_start_at`),
  CONSTRAINT `fk_incidents_endpoint` FOREIGN KEY (`endpoint_id`) REFERENCES `endpoints` (`endpoint_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `incident_alerts` (
  `incident_alert_id` BIGINT NOT NULL,
  `incident_id` BIGINT NOT NULL,
  `alert_id` BIGINT NOT NULL,
  `linked_at` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`incident_alert_id`),
  UNIQUE KEY `uq_incident_alerts_pair` (`incident_id`, `alert_id`),
  CONSTRAINT `fk_incident_alerts_incident` FOREIGN KEY (`incident_id`) REFERENCES `incidents` (`incident_id`),
  CONSTRAINT `fk_incident_alerts_alert` FOREIGN KEY (`alert_id`) REFERENCES `alerts` (`alert_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
