CREATE TABLE `users` (
  `user_id` BIGINT NOT NULL COMMENT 'Dashboard 사용자 식별자',
  `login_id` VARCHAR(64) NOT NULL COMMENT '3~64자 사용자 지정 Dashboard 로그인 ID',
  `password_hash` VARCHAR(255) NOT NULL COMMENT '비밀번호 Hash',
  `name` VARCHAR(100) NOT NULL COMMENT '사용자 이름',
  `role` VARCHAR(30) NOT NULL COMMENT 'ADMIN, ANALYST 또는 VIEWER',
  `status` VARCHAR(30) NOT NULL COMMENT 'ACTIVE 또는 DISABLED Dashboard 계정 상태',
  `locale` VARCHAR(2) NOT NULL DEFAULT 'EN' COMMENT 'EN 또는 KO 사용자 UI 언어 설정',
  `last_login_at` DATETIME NULL COMMENT '마지막 로그인 시각',
  `created_at` DATETIME NOT NULL COMMENT '생성 시각',
  `updated_at` DATETIME NOT NULL COMMENT '수정 시각',
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '소프트 삭제 여부',
  PRIMARY KEY (`user_id`),
  CONSTRAINT `ck_users_locale` CHECK (`locale` IN ('EN', 'KO')),
  UNIQUE KEY `uq_users_login_id_active` (`login_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='[PostgreSQL] 실제 unique index는 LOWER(login_id), WHERE is_delete=FALSE 조건을 사용하는 Dashboard RBAC 사용자';

CREATE TABLE `endpoints` (
  `endpoint_id` BIGINT NOT NULL COMMENT '엔드포인트 식별자',
  `agent_id` VARCHAR(64) NOT NULL COMMENT 'Agent 불변 식별자',
  `hostname` VARCHAR(255) NOT NULL COMMENT '호스트 이름',
  `os_type` VARCHAR(30) NOT NULL COMMENT 'WINDOWS 또는 MACOS',
  `os_version` VARCHAR(100) NULL COMMENT '운영체제 버전',
  `ip_address` VARCHAR(45) NULL COMMENT '마지막 보고 IP 주소',
  `agent_version` VARCHAR(50) NULL COMMENT 'Agent 버전',
  `agent_build_id` VARCHAR(200) NULL COMMENT 'Agent 빌드 식별자',
  `agent_arch` VARCHAR(20) NULL COMMENT 'X64 또는 ARM64',
  `capability_codes_json` LONGTEXT NOT NULL COMMENT 'Agent 지원 기능 목록 JSON',
  `sensor_health_json` LONGTEXT NOT NULL COMMENT 'Collector별 상태 JSON',
  `registered_at` DATETIME NOT NULL COMMENT '최초 등록 시각',
  `status` VARCHAR(30) NOT NULL COMMENT 'Heartbeat ONLINE, 2분 미수신 OFFLINE, 최우선 RETIRED',
  `last_seen_at` DATETIME NULL COMMENT '마지막 Heartbeat 수신 시각',
  `created_at` DATETIME NOT NULL COMMENT '생성 시각',
  `updated_at` DATETIME NOT NULL COMMENT '수정 시각',
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '소프트 삭제 여부',
  PRIMARY KEY (`endpoint_id`),
  UNIQUE KEY `uq_endpoints_agent_id` (`agent_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='[PostgreSQL] 엔드포인트와 Agent 상태';

CREATE TABLE `agent_auth_keys` (
  `agent_auth_key_id` BIGINT NOT NULL COMMENT 'Agent 인증서 이력 식별자',
  `endpoint_id` BIGINT NOT NULL COMMENT '인증서를 사용하는 엔드포인트 식별자',
  `cert_fingerprint` VARCHAR(128) NOT NULL COMMENT '인증서 SHA-256 Fingerprint',
  `cert_subject` VARCHAR(500) NOT NULL COMMENT '인증서 Subject',
  `cert_san_agent_id` VARCHAR(64) NOT NULL COMMENT '인증서 SAN에 포함된 Agent ID',
  `issued_at` DATETIME NOT NULL COMMENT '인증서 발급 시각',
  `expires_at` DATETIME NOT NULL COMMENT '인증서 만료 시각',
  `revoked_at` DATETIME NULL COMMENT '인증서 폐기 시각',
  `created_at` DATETIME NOT NULL COMMENT '생성 시각',
  `updated_at` DATETIME NOT NULL COMMENT '수정 시각',
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '소프트 삭제 여부',
  PRIMARY KEY (`agent_auth_key_id`),
  UNIQUE KEY `uq_agent_auth_keys_fingerprint` (`cert_fingerprint`),
  KEY `idx_agent_auth_keys_endpoint` (`endpoint_id`),
  CONSTRAINT `fk_agent_auth_keys_endpoint` FOREIGN KEY (`endpoint_id`) REFERENCES `endpoints` (`endpoint_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='[PostgreSQL] 관리자 CLI가 발급한 URI SAN Agent mTLS 인증서 이력과 Rotation';

CREATE TABLE `audit_logs` (
  `audit_log_id` BIGINT NOT NULL COMMENT '감사 로그 식별자',
  `actor_type` VARCHAR(30) NOT NULL COMMENT 'USER, AGENT 또는 SYSTEM',
  `actor_identifier` VARCHAR(255) NOT NULL COMMENT '행위자 식별 정보 스냅샷',
  `action` VARCHAR(100) NOT NULL COMMENT '감사 Action 코드',
  `resource_type` VARCHAR(50) NOT NULL COMMENT '변경된 Resource 종류',
  `resource_id` VARCHAR(255) NOT NULL COMMENT '변경된 Resource 식별자 스냅샷',
  `before_json` LONGTEXT NULL COMMENT '변경 전 값 JSON',
  `after_json` LONGTEXT NULL COMMENT '변경 후 값 JSON',
  `request_id` VARCHAR(100) NOT NULL COMMENT '요청 추적 식별자',
  `created_at` DATETIME NOT NULL COMMENT '감사 로그 생성 시각',
  PRIMARY KEY (`audit_log_id`),
  KEY `idx_audit_logs_resource_created` (`resource_type`, `resource_id`, `created_at`),
  KEY `idx_audit_logs_request_id` (`request_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='[PostgreSQL] 수정과 삭제가 금지된 Append-only Control-plane 감사 로그';

CREATE TABLE `ingest_metadata` (
  `endpoint_id` BIGINT NOT NULL COMMENT '엔드포인트 식별자',
  `bucket_start_at` DATETIME NOT NULL COMMENT 'UTC 시간 버킷 시작 시각',
  `bucket_end_at` DATETIME NOT NULL COMMENT 'UTC 시간 버킷 종료 시각',
  `storage_backend` VARCHAR(30) NOT NULL COMMENT 'CLICKHOUSE 또는 S3',
  `storage_class` VARCHAR(50) NOT NULL COMMENT 'HOT 또는 GLACIER_FLEXIBLE_RETRIEVAL',
  `storage_status` VARCHAR(30) NOT NULL COMMENT 'HOT, ARCHIVED, RESTORE_REQUESTED, RESTORED, RESTORE_FAILED 또는 EXPIRED',
  `storage_path` VARCHAR(1000) NOT NULL COMMENT 'Endpoint별 ClickHouse 논리 조회 Locator 또는 복원 전후 동일한 S3 Object Key',
  `event_count` BIGINT NOT NULL DEFAULT 0 COMMENT '버킷 이벤트 수',
  `size_bytes` BIGINT NULL COMMENT '버킷 또는 Object 크기',
  `checksum_sha256` CHAR(64) NULL COMMENT 'Archive Object SHA-256',
  `archived_at` DATETIME NULL COMMENT 'Archive 생성 시각',
  `archive_verified_at` DATETIME NULL COMMENT 'Archive Checksum 검증 완료 시각',
  `restore_requested_at` DATETIME NULL COMMENT 'RestoreObject 요청 시각',
  `restored_at` DATETIME NULL COMMENT 'RestoreObject 임시 복원 완료 시각',
  `restore_expires_at` DATETIME NULL COMMENT '7일 임시 복원 만료 시각',
  `last_error` TEXT NULL COMMENT '마지막 Archive 또는 복원 오류',
  `created_at` DATETIME NOT NULL COMMENT '생성 시각',
  `updated_at` DATETIME NOT NULL COMMENT '수정 시각',
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '소프트 삭제 여부',
  PRIMARY KEY (`endpoint_id`, `bucket_start_at`, `storage_backend`, `storage_class`),
  UNIQUE KEY `uq_ingest_metadata_storage_path` (`storage_backend`, `storage_path`),
  CONSTRAINT `fk_ingest_metadata_endpoint` FOREIGN KEY (`endpoint_id`) REFERENCES `endpoints` (`endpoint_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='[PostgreSQL] 공유 UTC DAY ClickHouse Partition과 Endpoint별 Parquet Object를 연결하는 Archive 및 RestoreObject 카탈로그';

CREATE TABLE `local_event_buffer` (
  `local_event_buffer_id` BIGINT NOT NULL COMMENT 'Agent SQLite 로컬 버퍼 행 식별자',
  `endpoint_id` BIGINT NULL COMMENT '등록된 엔드포인트 식별자',
  `event_id` CHAR(36) NOT NULL COMMENT '전역 이벤트 식별자',
  `batch_id` CHAR(36) NULL COMMENT '전송 묶음 추적 식별자',
  `event_type` VARCHAR(50) NOT NULL COMMENT '이벤트 종류',
  `payload_json` LONGTEXT NOT NULL COMMENT '정규화된 메타데이터 이벤트 JSON',
  `collected_at` DATETIME NOT NULL COMMENT 'Agent 수집 시각',
  `status` VARCHAR(30) NOT NULL DEFAULT 'PENDING' COMMENT '전송 대기 또는 실패 상태',
  `retry_count` INT NOT NULL DEFAULT 0 COMMENT '전송 재시도 횟수',
  `last_error` TEXT NULL COMMENT '마지막 전송 오류',
  `next_retry_at` DATETIME NULL COMMENT '다음 전송 재시도 시각',
  `created_at` DATETIME NOT NULL COMMENT '생성 시각',
  `updated_at` DATETIME NOT NULL COMMENT '수정 시각',
  PRIMARY KEY (`local_event_buffer_id`),
  UNIQUE KEY `uq_local_event_buffer_event_id` (`event_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='[SQLite] Collector ACK 전 메타데이터 이벤트 임시 버퍼';

CREATE TABLE `event_failures` (
  `failure_id` CHAR(36) NOT NULL COMMENT '원본 Kafka 위치와 Consumer 및 Stage 기반 UUIDv5',
  `event_id` CHAR(36) NULL COMMENT '실패한 원본 이벤트 식별자',
  `endpoint_id` BIGINT NULL COMMENT '관련 엔드포인트 식별자',
  `source_topic` VARCHAR(200) NOT NULL COMMENT '실패 이벤트가 들어온 Kafka 토픽',
  `source_partition` INT NOT NULL COMMENT '원본 Kafka 파티션',
  `source_offset` BIGINT NOT NULL COMMENT '원본 Kafka 오프셋',
  `consumer_name` VARCHAR(100) NOT NULL COMMENT '실패가 발생한 Consumer 이름',
  `failure_stage` VARCHAR(100) NOT NULL COMMENT '실패 처리 단계',
  `failure_code` VARCHAR(100) NULL COMMENT '안정된 오류 코드',
  `error_message` TEXT NOT NULL COMMENT '오류 설명',
  `retryable` TINYINT(1) NOT NULL COMMENT '관리자 수동 재처리 가능 여부',
  `retry_count` INT NOT NULL DEFAULT 0 COMMENT 'Worker 내부 재시도 횟수',
  `payload_object_key` VARCHAR(1000) NOT NULL COMMENT 'failures/{failureId}/payload.json.gz 결정적 S3 경로',
  `payload_sha256` CHAR(64) NOT NULL COMMENT '멱등 및 충돌 판정용 deterministic gzip Object SHA-256',
  `payload_size_bytes` BIGINT NOT NULL COMMENT '저장된 deterministic gzip Object Byte 크기',
  `status` VARCHAR(30) NOT NULL COMMENT '실패 또는 수동 재처리 결과 상태',
  `failed_at` DATETIME NOT NULL COMMENT '최초 실패 시각',
  `replay_count` INT NOT NULL DEFAULT 0 COMMENT '관리자 CLI 수동 재처리 횟수',
  `last_replayed_at` DATETIME NULL COMMENT '마지막 수동 재처리 시각',
  `reprocess_outcome` VARCHAR(100) NULL COMMENT '마지막 재처리 결과 요약',
  `resolved_at` DATETIME NULL COMMENT '재처리 성공 시각',
  `retention_expires_at` DATETIME NOT NULL COMMENT '최초 실패부터 90일 S3 원문 보존 만료 시각',
  `created_at` DATETIME NOT NULL COMMENT '생성 시각',
  `updated_at` DATETIME NOT NULL COMMENT '최신 결과 갱신 시각',
  PRIMARY KEY (`failure_id`),
  KEY `idx_event_failures_endpoint_failed` (`endpoint_id`, `failed_at`),
  KEY `idx_event_failures_status_failed` (`status`, `failed_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='[ClickHouse] 결정적 Failure ID와 S3 원문 위치 및 수동 재처리 결과를 최초 실패부터 97일 보존';

CREATE TABLE `edr_events` (
  `event_id` CHAR(36) NOT NULL COMMENT '전역 이벤트 식별자',
  `batch_id` CHAR(36) NOT NULL COMMENT '전송 묶음 추적 식별자',
  `endpoint_id` BIGINT NOT NULL COMMENT '논리적으로 연결된 엔드포인트 식별자',
  `agent_id` VARCHAR(64) NOT NULL COMMENT 'Agent 식별자',
  `hostname` VARCHAR(255) NOT NULL COMMENT '이벤트 수집 당시 호스트 이름',
  `os_type` VARCHAR(30) NOT NULL COMMENT 'WINDOWS 또는 MACOS',
  `ip_address` VARCHAR(45) NULL COMMENT '이벤트 수집 당시 IP 주소',
  `event_type` VARCHAR(50) NOT NULL COMMENT 'Process, Network, File, DNS 또는 L7 이벤트 종류',
  `occurred_at` DATETIME NOT NULL COMMENT '단말에서 이벤트가 발생한 시각',
  `ingested_at` DATETIME NOT NULL COMMENT '서버가 이벤트를 수신한 시각',
  `process_name` VARCHAR(255) NULL COMMENT '프로세스 이름',
  `process_path` VARCHAR(1000) NULL COMMENT '프로세스 실행 경로',
  `pid` BIGINT NULL COMMENT '프로세스 식별자',
  `ppid` BIGINT NULL COMMENT '부모 프로세스 식별자',
  `command_line` TEXT NULL COMMENT '프로세스 명령행',
  `user_name` VARCHAR(255) NULL COMMENT '프로세스 실행 사용자 이름',
  `file_path` VARCHAR(1000) NULL COMMENT '파일 경로',
  `file_action` VARCHAR(50) NULL COMMENT '파일 변경 동작',
  `file_hash_sha256` CHAR(64) NULL COMMENT '파일 SHA-256',
  `remote_ip` VARCHAR(45) NULL COMMENT '원격 IP 주소',
  `remote_domain` VARCHAR(255) NULL COMMENT '원격 도메인',
  `remote_port` INT NULL COMMENT '원격 포트',
  `protocol` VARCHAR(30) NULL COMMENT '네트워크 프로토콜',
  `dns_query` VARCHAR(500) NULL COMMENT 'DNS 질의 이름',
  `dns_record_type` VARCHAR(20) NULL COMMENT 'DNS Record 종류',
  `dns_response_code` VARCHAR(30) NULL COMMENT 'DNS 응답 코드',
  `dns_answers_json` LONGTEXT NULL COMMENT 'DNS 응답 목록 JSON',
  `l7_protocol` VARCHAR(30) NULL COMMENT 'HTTP 또는 TLS 등 L7 프로토콜',
  `http_method` VARCHAR(20) NULL COMMENT 'HTTP Method',
  `http_host` VARCHAR(500) NULL COMMENT 'HTTP Host',
  `url` TEXT NULL COMMENT 'Query와 Fragment를 제거한 HTTP URL Path',
  `http_status_code` INT NULL COMMENT 'HTTP 응답 상태 코드',
  `http_user_agent` TEXT NULL COMMENT 'HTTP User-Agent',
  `tls_sni` VARCHAR(500) NULL COMMENT 'TLS Server Name Indication',
  `tls_version` VARCHAR(30) NULL COMMENT 'TLS 버전',
  `tls_certificate_subject` VARCHAR(1000) NULL COMMENT 'TLS 인증서 Subject',
  `tls_certificate_issuer` VARCHAR(1000) NULL COMMENT 'TLS 인증서 Issuer',
  `tls_certificate_sha256` CHAR(64) NULL COMMENT 'TLS 인증서 SHA-256',
  `raw_payload` LONGTEXT NOT NULL COMMENT '원본 PCAP이 아닌 정규화 메타데이터 이벤트 JSON',
  `payload_sha256` CHAR(64) NOT NULL COMMENT '정규화 이벤트 Payload SHA-256',
  `schema_version` INT NOT NULL COMMENT '이벤트 Schema 버전',
  `created_at` DATETIME NOT NULL COMMENT '생성 시각',
  `updated_at` DATETIME NOT NULL COMMENT '수정 시각',
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '논리 삭제 표시',
  PRIMARY KEY (`endpoint_id`, `occurred_at`, `event_type`, `event_id`),
  UNIQUE KEY `uq_edr_events_event_id` (`event_id`),
  KEY `idx_edr_events_type_occurred` (`event_type`, `occurred_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='[ClickHouse] Process, Network, File, DNS, L7 메타데이터 이벤트';

CREATE TABLE `alerts` (
  `alert_id` BIGINT NOT NULL COMMENT 'Alert 식별자',
  `endpoint_id` BIGINT NOT NULL COMMENT '관련 엔드포인트 식별자',
  `event_id` CHAR(36) NOT NULL COMMENT '탐지 근거 이벤트 식별자',
  `event_occurred_at` DATETIME NOT NULL COMMENT '근거 이벤트 발생 시각',
  `batch_id` CHAR(36) NULL COMMENT '근거 이벤트 전송 묶음 식별자',
  `agent_id` VARCHAR(64) NOT NULL COMMENT '탐지 대상 Agent 식별자',
  `rule_code` VARCHAR(100) NOT NULL COMMENT '탐지 Rule 코드',
  `rule_name` VARCHAR(200) NOT NULL COMMENT '탐지 Rule 이름',
  `rule_version` INT NOT NULL COMMENT '탐지 Rule 버전',
  `mitre_tactic_code` VARCHAR(20) NOT NULL COMMENT '활성 Rule YAML의 필수 MITRE ATT&CK Tactic 코드',
  `mitre_tactic_name` VARCHAR(100) NOT NULL COMMENT '고정 ATT&CK Mapping에서 변환한 Tactic 이름',
  `mitre_technique_code` VARCHAR(30) NOT NULL COMMENT '활성 Rule YAML의 필수 MITRE ATT&CK Technique 코드',
  `mitre_technique_name` VARCHAR(200) NOT NULL COMMENT '고정 ATT&CK Mapping에서 변환한 Technique 이름',
  `title` VARCHAR(200) NOT NULL COMMENT 'Alert 제목',
  `summary` TEXT NOT NULL COMMENT 'Alert 요약',
  `severity` VARCHAR(20) NOT NULL COMMENT 'LOW, MEDIUM, HIGH 또는 CRITICAL',
  `risk_score` DECIMAL(5,2) NOT NULL COMMENT '위험 점수',
  `status` VARCHAR(30) NOT NULL COMMENT 'OPEN, IN_PROGRESS 또는 RESOLVED',
  `detected_at` DATETIME NOT NULL COMMENT '탐지 시각',
  `created_at` DATETIME NOT NULL COMMENT '생성 시각',
  `updated_at` DATETIME NOT NULL COMMENT '수정 시각',
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '소프트 삭제 여부',
  PRIMARY KEY (`alert_id`),
  UNIQUE KEY `uq_alerts_event_rule` (`event_id`, `rule_code`, `rule_version`),
  KEY `idx_alerts_endpoint_detected` (`endpoint_id`, `detected_at`),
  CONSTRAINT `fk_alerts_endpoint` FOREIGN KEY (`endpoint_id`) REFERENCES `endpoints` (`endpoint_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='[PostgreSQL] 모든 활성 Rule의 필수 MITRE ATT&CK Mapping을 포함한 탐지 결과';

CREATE TABLE `incidents` (
  `incident_id` BIGINT NOT NULL COMMENT 'Incident 식별자',
  `endpoint_id` BIGINT NOT NULL COMMENT '관련 엔드포인트 식별자',
  `correlation_key` VARCHAR(255) NOT NULL COMMENT 'Rule에서 정의한 상관관계 Key',
  `window_start_at` DATETIME NOT NULL COMMENT '상관관계 시간 구간 시작',
  `window_end_at` DATETIME NOT NULL COMMENT '상관관계 시간 구간 종료',
  `title` VARCHAR(200) NOT NULL COMMENT 'Incident 제목',
  `description` TEXT NULL COMMENT 'Incident 설명',
  `severity` VARCHAR(20) NOT NULL COMMENT '심각도',
  `status` VARCHAR(30) NOT NULL COMMENT '생성 시 OPEN, Window 만료 시 자동 CLOSED',
  `first_detected_at` DATETIME NOT NULL COMMENT '최초 Alert 탐지 시각',
  `last_detected_at` DATETIME NOT NULL COMMENT '최근 Alert 탐지 시각',
  `closed_at` DATETIME NULL COMMENT '자동 종료 시 window_end_at과 같은 시각',
  `created_at` DATETIME NOT NULL COMMENT '생성 시각',
  `updated_at` DATETIME NOT NULL COMMENT '수정 시각',
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '소프트 삭제 여부',
  PRIMARY KEY (`incident_id`),
  UNIQUE KEY `uq_incidents_correlation` (`endpoint_id`, `correlation_key`, `window_start_at`),
  CONSTRAINT `fk_incidents_endpoint` FOREIGN KEY (`endpoint_id`) REFERENCES `endpoints` (`endpoint_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='[PostgreSQL] Rule Window 만료 시 자동 종료되는 읽기 전용 Incident Projection';

CREATE TABLE `incident_alerts` (
  `incident_alert_id` BIGINT NOT NULL COMMENT 'Incident와 Alert 연결 식별자',
  `incident_id` BIGINT NOT NULL COMMENT 'Incident 식별자',
  `alert_id` BIGINT NOT NULL COMMENT 'Alert 식별자',
  `linked_at` DATETIME NOT NULL COMMENT '자동 연결 시각',
  `created_at` DATETIME NOT NULL COMMENT '생성 시각',
  `updated_at` DATETIME NOT NULL COMMENT '수정 시각',
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '소프트 삭제 여부',
  PRIMARY KEY (`incident_alert_id`),
  UNIQUE KEY `uq_incident_alerts_pair` (`incident_id`, `alert_id`),
  CONSTRAINT `fk_incident_alerts_incident` FOREIGN KEY (`incident_id`) REFERENCES `incidents` (`incident_id`),
  CONSTRAINT `fk_incident_alerts_alert` FOREIGN KEY (`alert_id`) REFERENCES `alerts` (`alert_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='[PostgreSQL] Incident와 Alert의 다대다 연결';
