import type { DashboardLayoutDto, SuccessEnvelope } from "../src/contracts";

export const dashboardLayoutV1Fixture = {
  data: {
    dashboardKey: "overview",
    layoutVersion: 1,
    revision: 7,
    isDefault: false,
    widgets: [
      { id: "edr-state", x: 0, y: 0, w: 12, h: 2, hidden: false },
      { id: "kpi-events", x: 0, y: 2, w: 2, h: 2, hidden: true },
      { id: "kpi-alerts", x: 2, y: 2, w: 2, h: 2, hidden: false },
      { id: "kpi-open-incidents", x: 4, y: 2, w: 2, h: 2, hidden: false },
      { id: "kpi-online-endpoints", x: 6, y: 2, w: 2, h: 2, hidden: false },
      { id: "kpi-event-failures", x: 8, y: 2, w: 2, h: 2, hidden: false },
      { id: "kpi-storage-buckets", x: 10, y: 2, w: 2, h: 2, hidden: false },
      { id: "alert-severity", x: 0, y: 4, w: 4, h: 5, hidden: false },
      { id: "event-volume", x: 0, y: 43, w: 12, h: 6, hidden: false },
      { id: "alert-volume", x: 0, y: 9, w: 6, h: 5, hidden: false },
      { id: "incident-activity", x: 6, y: 9, w: 6, h: 5, hidden: false },
      { id: "endpoint-risk", x: 0, y: 14, w: 4, h: 5, hidden: false },
      { id: "highest-risk-endpoints", x: 4, y: 14, w: 4, h: 5, hidden: false },
      { id: "incident-queue", x: 8, y: 14, w: 4, h: 5, hidden: false },
      { id: "response-guidance", x: 0, y: 19, w: 12, h: 5, hidden: false },
      { id: "endpoint-operating-systems", x: 0, y: 24, w: 4, h: 4, hidden: false },
      { id: "sensor-health", x: 4, y: 24, w: 4, h: 4, hidden: false },
      { id: "top-rules", x: 8, y: 24, w: 4, h: 4, hidden: false },
      { id: "mitre-distribution", x: 0, y: 28, w: 6, h: 5, hidden: false },
      { id: "process-network-signals", x: 6, y: 28, w: 6, h: 5, hidden: false },
      { id: "file-dns-l7-signals", x: 0, y: 33, w: 6, h: 5, hidden: false },
      { id: "failure-distribution", x: 6, y: 33, w: 6, h: 5, hidden: false },
      { id: "storage-distribution", x: 0, y: 38, w: 6, h: 5, hidden: false },
    ],
  },
  meta: { requestId: "req_dashboard_layout_v1_fixture" },
} satisfies SuccessEnvelope<DashboardLayoutDto>;
