import { useQuery } from "@tanstack/react-query";
import { Link, useSearchParams } from "react-router-dom";
import { api } from "../api/endpoints";
import { readTimeFilter, TimeFilterFields } from "../components/filters";
import { DataTable, EmptyState, ErrorState, Field, GlobalFilterBar, PageHeader, Pagination, Panel, Skeleton, StatusPill } from "../components/ui";
import type { IncidentListQuery } from "../contracts";
import { formatDateTime } from "../lib/format";
import { allowedValue, positiveInteger } from "../lib/params";
import { numberParam, updateParams } from "../lib/url";

export function IncidentsPage() {
  const [params, setParams] = useSearchParams();
  const time = readTimeFilter(params);
  const status = allowedValue(params.get("status"), ["OPEN", "CLOSED"] as const);
  const severity = allowedValue(params.get("severity"), ["LOW", "MEDIUM", "HIGH", "CRITICAL"] as const);
  const sortOrder = allowedValue(params.get("sortOrder"), ["asc", "desc"] as const) ?? "desc";
  const endpointId = positiveInteger(params.get("endpointId"));
  const query: IncidentListQuery = { ...time.query, page: numberParam(params, "page", 1), size: numberParam(params, "size", 50), sortOrder };
  if (status) query.status = status;
  if (severity) query.severity = severity;
  if (endpointId) query.endpointId = endpointId;
  const result = useQuery({ queryKey: ["incidents", query], queryFn: ({ signal }) => api.incidents(query, signal), enabled: time.valid });

  return <div className="page-stack">
    <PageHeader eyebrow="CORRELATION" title="Incidents" description="Read-only correlated Alert windows generated by Detection Workers." />
    <GlobalFilterBar hasFilters={params.size > 0} onClear={() => setParams({})}>
      <TimeFilterFields params={params} setParams={setParams} />
      <Field label="Status"><select onChange={(event) => setParams(updateParams(params, { status: event.target.value }))} value={status ?? ""}><option value="">All statuses</option><option>OPEN</option><option>CLOSED</option></select></Field>
      <Field label="Severity"><select onChange={(event) => setParams(updateParams(params, { severity: event.target.value }))} value={severity ?? ""}><option value="">All severities</option><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select></Field>
      <Field label="Endpoint ID"><input inputMode="numeric" onChange={(event) => setParams(updateParams(params, { endpointId: event.target.value }))} value={params.get("endpointId") ?? ""} /></Field>
      <Field label="Order"><select onChange={(event) => setParams(updateParams(params, { sortOrder: event.target.value }))} value={sortOrder}><option value="desc">Newest first</option><option value="asc">Oldest first</option></select></Field>
    </GlobalFilterBar>
    {result.isPending && time.valid ? <Skeleton rows={7} /> : null}
    {result.error ? <ErrorState error={result.error} onRetry={() => void result.refetch()} /> : null}
    {result.data ? <Panel title="Incident workbench" subtitle={`${result.data.data.total} read-only Incident records`}>
      {result.data.data.items.length ? <><DataTable label="Incident workbench"><thead><tr><th scope="col">Incident</th><th scope="col">Endpoint</th><th scope="col">Severity</th><th scope="col">Status</th><th scope="col">Alerts</th><th scope="col">Window</th><th scope="col" aria-sort={sortOrder === "desc" ? "descending" : "ascending"}>Last detected</th></tr></thead><tbody>{result.data.data.items.map((incident) => <tr key={incident.incidentId}><td><Link className="table-primary" to={`/incidents/${incident.incidentId}`}><strong>{incident.title}</strong><code>{incident.correlationKey}</code></Link></td><td><Link to={`/endpoints/${incident.endpointId}`}>{incident.endpointId}</Link></td><td><StatusPill value={incident.severity} /></td><td><StatusPill value={incident.status} /></td><td>{incident.alertCount}</td><td>{formatDateTime(incident.windowStartAt)}<small>to {formatDateTime(incident.windowEndAt)}</small></td><td>{formatDateTime(incident.lastDetectedAt)}</td></tr>)}</tbody></DataTable><Pagination page={result.data.data} /></> : <EmptyState title="No Incidents found" message={params.size ? "No Incidents match the current filters." : "No correlated Incidents exist in this time range."} />}
    </Panel> : null}
  </div>;
}
