CREATE TABLE IF NOT EXISTS edr_events (
    event_id UUID,
    batch_id UUID,
    endpoint_id UInt64,
    agent_id String,
    hostname String,
    os_type LowCardinality(String),
    ip_address Nullable(String),
    event_type LowCardinality(String),
    occurred_at DateTime64(3, 'UTC'),
    ingested_at DateTime64(3, 'UTC'),
    process_name Nullable(String),
    process_path Nullable(String),
    pid Nullable(UInt64),
    ppid Nullable(UInt64),
    command_line Nullable(String),
    user_name Nullable(String),
    file_path Nullable(String),
    file_action Nullable(String),
    file_hash_sha256 Nullable(String),
    remote_ip Nullable(String),
    remote_domain Nullable(String),
    remote_port Nullable(UInt16),
    protocol Nullable(String),
    dns_query Nullable(String),
    dns_record_type Nullable(String),
    dns_response_code Nullable(String),
    dns_answers_json Nullable(String),
    l7_protocol Nullable(String),
    http_method Nullable(String),
    http_host Nullable(String),
    url Nullable(String),
    http_status_code Nullable(UInt16),
    http_user_agent Nullable(String),
    tls_sni Nullable(String),
    tls_version Nullable(String),
    tls_certificate_subject Nullable(String),
    tls_certificate_issuer Nullable(String),
    tls_certificate_sha256 Nullable(String),
    raw_payload String,
    payload_sha256 FixedString(64),
    schema_version UInt16,
    created_at DateTime64(3, 'UTC'),
    updated_at DateTime64(3, 'UTC'),
    is_delete UInt8 DEFAULT 0
)
ENGINE = ReplacingMergeTree(updated_at)
PARTITION BY toDate(occurred_at)
ORDER BY (endpoint_id, occurred_at, event_type, event_id);

CREATE TABLE IF NOT EXISTS event_failures (
    failure_id UUID,
    event_id Nullable(UUID),
    endpoint_id Nullable(UInt64),
    source_topic LowCardinality(String),
    source_partition UInt32,
    source_offset UInt64,
    consumer_name LowCardinality(String),
    failure_stage LowCardinality(String),
    failure_code Nullable(String),
    error_message String,
    retryable UInt8,
    retry_count UInt16,
    payload_object_key String,
    payload_sha256 FixedString(64),
    payload_size_bytes UInt64,
    status LowCardinality(String),
    failed_at DateTime64(3, 'UTC'),
    replay_count UInt16,
    last_replayed_at Nullable(DateTime64(3, 'UTC')),
    reprocess_outcome Nullable(String),
    resolved_at Nullable(DateTime64(3, 'UTC')),
    retention_expires_at DateTime64(3, 'UTC'),
    created_at DateTime64(3, 'UTC'),
    updated_at DateTime64(3, 'UTC')
)
ENGINE = ReplacingMergeTree(updated_at)
PARTITION BY toYYYYMM(failed_at)
ORDER BY failure_id
TTL toDateTime(failed_at) + INTERVAL 97 DAY DELETE;
