from __future__ import annotations

import argparse
import json
import os
import secrets
import shutil
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

from tools.secure_files import protect_private_path

ROOT = Path(__file__).parents[1]
ENV_FILE = ROOT / ".env"
RUNTIME_DIR = ROOT / "runtime" / "demo"
CREDENTIALS_FILE = RUNTIME_DIR / "credentials.json"
ADMIN_LOGIN_ID = "admin"


def _tool(name: str) -> str:
    executable = shutil.which(name)
    if executable is None:
        raise RuntimeError(f"required command is not installed or not on PATH: {name}")
    return executable


def _run(arguments: list[str], *, env: dict[str, str] | None = None) -> None:
    print(f"+ {' '.join(arguments)}")
    subprocess.run(arguments, cwd=ROOT, check=True, env=env, text=True)


def _read_env() -> dict[str, str]:
    values = os.environ.copy()
    if not ENV_FILE.exists():
        return values
    for raw_line in ENV_FILE.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key] = value
    return values


def _write_local_env() -> bool:
    if ENV_FILE.exists():
        return False
    postgres_password = secrets.token_hex(24)
    clickhouse_password = secrets.token_hex(24)
    minio_password = secrets.token_hex(24)
    content = f"""# Generated by tools.local_demo. Local use only; this file is gitignored.
EDR_ENV=local
EDR_LOG_LEVEL=INFO
EDR_JWT_SECRET={secrets.token_hex(32)}
EDR_ACCESS_TOKEN_TTL_SECONDS=43200
EDR_AWS_REGION=us-east-1

POSTGRES_DB=edr
POSTGRES_USER=edr
POSTGRES_PASSWORD={postgres_password}
POSTGRES_HOST_PORT=55432
EDR_POSTGRES_DSN=postgresql://edr:{postgres_password}@127.0.0.1:55432/edr

CLICKHOUSE_DB=edr
CLICKHOUSE_USER=edr
CLICKHOUSE_PASSWORD={clickhouse_password}
CLICKHOUSE_HTTP_HOST_PORT=58123
CLICKHOUSE_NATIVE_HOST_PORT=59009
EDR_CLICKHOUSE_DSN=http://edr:{clickhouse_password}@127.0.0.1:58123/edr

KAFKA_HOST_PORT=59092
EDR_KAFKA_BOOTSTRAP_SERVERS=127.0.0.1:59092
EDR_KAFKA_RAW_TOPIC=telemetry.raw
EDR_KAFKA_VALIDATED_TOPIC=telemetry.validated
EDR_KAFKA_PARTITIONS_PER_TOPIC=2
EDR_KAFKA_REPLICATION_FACTOR=1
EDR_EVENT_STORAGE_CONSUMER_GROUP=edr-event-storage-v1
EDR_DETECTION_CONSUMER_GROUP=edr-detection-v1

MINIO_ROOT_USER=edr-local
MINIO_ROOT_PASSWORD={minio_password}
MINIO_API_HOST_PORT=59000
MINIO_CONSOLE_HOST_PORT=59001
EDR_S3_ENDPOINT_URL=http://127.0.0.1:59000
EDR_S3_ACCESS_KEY_ID=edr-local
EDR_S3_SECRET_ACCESS_KEY={minio_password}
EDR_S3_BUCKET=edr-failures

NGINX_HTTP_HOST_PORT=8080
NGINX_MTLS_HOST_PORT=8443
"""
    ENV_FILE.write_text(content, encoding="utf-8")
    protect_private_path(ENV_FILE)
    return True


def _ensure_credentials() -> dict[str, str]:
    RUNTIME_DIR.mkdir(mode=0o700, parents=True, exist_ok=True)
    protect_private_path(RUNTIME_DIR, directory=True)
    if CREDENTIALS_FILE.exists():
        credentials = json.loads(CREDENTIALS_FILE.read_text(encoding="utf-8"))
        if "loginId" not in credentials and "email" in credentials:
            credentials = {"loginId": credentials["email"], "password": credentials["password"]}
            CREDENTIALS_FILE.write_text(json.dumps(credentials, indent=2) + "\n", encoding="utf-8")
            protect_private_path(CREDENTIALS_FILE)
        return credentials
    credentials = {"loginId": ADMIN_LOGIN_ID, "password": secrets.token_urlsafe(18)}
    CREDENTIALS_FILE.write_text(json.dumps(credentials, indent=2) + "\n", encoding="utf-8")
    protect_private_path(CREDENTIALS_FILE)
    return credentials


def _compose(*arguments: str) -> list[str]:
    command = [_tool("docker"), "compose"]
    if ENV_FILE.exists():
        command.extend(("--env-file", str(ENV_FILE)))
    return [*command, *arguments]


def _check_docker() -> None:
    _run([_tool("docker"), "info"])


def _print_access() -> None:
    values = _read_env()
    http_port = values.get("NGINX_HTTP_HOST_PORT", "8080")
    mtls_port = values.get("NGINX_MTLS_HOST_PORT", "8443")
    print("\nEDR_C full Docker Compose environment is running")
    print(f"Dashboard: http://127.0.0.1:{http_port}")
    print(f"Swagger:   http://127.0.0.1:{http_port}/docs")
    print(f"Collector: https://127.0.0.1:{mtls_port} (mTLS only)")
    print(f"Credentials file: {CREDENTIALS_FILE}")


def setup() -> None:
    _check_docker()
    created = _write_local_env()
    _run(_compose("build"), env=_read_env())
    print("\nLocal Compose images are ready" + (" (new local secrets generated)" if created else ""))


def start(*, build: bool = False) -> None:
    _check_docker()
    _write_local_env()
    arguments = ["up", "-d"]
    if build:
        arguments.append("--build")
    arguments.append("--wait")
    _run(_compose(*arguments), env=_read_env())
    _print_access()


def _initialize() -> None:
    import clickhouse_connect
    import psycopg
    from botocore.exceptions import ClientError

    from backend.auth import hash_password
    from backend.kafka import ensure_topics
    from backend.runtime import create_s3_client
    from backend.settings import get_settings
    from backend.storage.migrations import apply_clickhouse_file, apply_postgres_file
    from backend.storage.postgres import UserRepository

    settings = get_settings()
    with psycopg.connect(settings.postgres_dsn.get_secret_value()) as connection:
        exists = connection.execute("SELECT to_regclass('public.users')").fetchone()[0]
        if exists is None:
            apply_postgres_file(connection, ROOT / "migrations/postgresql/0001_initial.up.sql")
        login_id_exists = connection.execute(
            """
            SELECT EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_schema = 'public' AND table_name = 'users' AND column_name = 'login_id'
            )
            """
        ).fetchone()[0]
        if not login_id_exists:
            apply_postgres_file(connection, ROOT / "migrations/postgresql/0002_user_login_id.up.sql")
        locale_exists = connection.execute(
            """
            SELECT EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_schema = 'public' AND table_name = 'users' AND column_name = 'locale'
            )
            """
        ).fetchone()[0]
        if not locale_exists:
            apply_postgres_file(connection, ROOT / "migrations/postgresql/0003_user_locale.up.sql")
        login_id_length = connection.execute(
            """
            SELECT character_maximum_length
            FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = 'users' AND column_name = 'login_id'
            """
        ).fetchone()[0]
        if login_id_length != 64:
            connection.execute("ALTER TABLE users ALTER COLUMN login_id TYPE VARCHAR(64)")
        credentials = _ensure_credentials()
        existing_admin = connection.execute(
            "SELECT 1 FROM users WHERE LOWER(login_id)=LOWER(%s) AND is_delete=FALSE", (credentials["loginId"],)
        ).fetchone()
        if existing_admin is None:
            UserRepository(connection).create_admin(
                login_id=credentials["loginId"],
                name="Local Demo Admin",
                password_hash=hash_password(credentials["password"]),
                now=datetime.now(UTC),
            )
    clickhouse = clickhouse_connect.get_client(
        dsn=settings.clickhouse_dsn.get_secret_value(), autogenerate_session_id=False
    )
    try:
        apply_clickhouse_file(clickhouse, ROOT / "migrations/clickhouse/0001_initial.up.sql")
    finally:
        clickhouse.close()
    s3 = create_s3_client(settings)
    try:
        s3.create_bucket(Bucket=settings.s3_bucket)
    except ClientError as error:
        if error.response.get("Error", {}).get("Code") not in {"BucketAlreadyExists", "BucketAlreadyOwnedByYou"}:
            raise
    ensure_topics(
        settings.kafka_bootstrap_servers,
        topics=settings.kafka_topics,
        partitions_per_topic=settings.kafka_partitions_per_topic,
        replication_factor=settings.kafka_replication_factor,
    )


def down() -> None:
    if shutil.which("docker") is not None:
        _run(_compose("down"), env=_read_env())
    print("EDR_C local Compose environment stopped. Data volumes were preserved.")


def status() -> int:
    result = subprocess.run(_compose("ps"), cwd=ROOT, env=_read_env(), text=True, check=False)
    return result.returncode


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Manage the EDR_C full Docker Compose development environment.")
    parser.add_argument("command", choices=["up", "setup", "start", "status", "down", "_initialize"])
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    arguments = parse_args(argv)
    try:
        if arguments.command == "up":
            start(build=True)
        elif arguments.command == "setup":
            setup()
        elif arguments.command == "start":
            start()
        elif arguments.command == "status":
            return status()
        elif arguments.command == "down":
            down()
        else:
            _initialize()
    except (RuntimeError, subprocess.CalledProcessError, OSError, ValueError) as error:
        print(f"local Compose environment failed: {error}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
